"""Database operations for the rhizome knowledge base."""

from .entries import (
    EntrySortKey,
    count_entries,
    count_entries_filtered,
    create_entry,
    delete_entry,
    get_entry,
    list_entries,
    list_entries_paginated,
    search_entries,
    update_entry,
)
from .relations import (
    CycleError,
    add_relation,
    get_dependency_chain,
    get_related_entries,
    remove_relation,
)
from .tags import (
    create_tag,
    get_entries_by_tag,
    list_tags,
    tag_entry,
    untag_entry,
)
from .flashcards import (
    activate_flashcard,
    apply_fsrs_card,
    apply_rating,
    commit_fsrs_card,
    count_flashcards,
    count_flashcards_by_topic,
    count_flashcards_by_topics,
    count_flashcards_for_entries,
    create_flashcard,
    get_due_flashcards,
    get_flashcard_entry_ids,
    get_flashcards_by_ids,
    link_flashcards_to_entry,
    list_flashcards_by_entries,
    list_flashcards_by_topic,
    list_flashcards_for_entries,
    list_flashcards_paginated,
    to_fsrs_card,
    unlink_flashcards_from_entry,
)
from .reviews import (
    add_review_interaction,
    complete_review_session,
    create_review_session,
    get_interaction_stats,
    get_review_session,
    get_review_session_entries,
    get_sessions_by_topics,
    list_review_interactions,
    update_session_ephemeral,
    update_session_instructions,
    update_session_plan,
    update_session_summary,
)
from .resolve import (
    AmbiguousResource,
    AmbiguousTopic,
    get_topic_path,
    resolve_resource,
    resolve_topic,
)
from .resources import (
    add_chunks,
    clear_chunks,
    compute_section_end_offsets,
    create_resource,
    delete_resource,
    get_chunks,
    get_chunks_for_section,
    get_resource,
    get_resource_with_content_and_sections,
    get_section_resource_ids,
    insert_sections,
    count_resources,
    link_chunks_to_sections,
    link_resource_to_topic,
    list_resources,
    list_resources_for_topic,
    list_resources_paginated,
    unlink_resource_from_topic,
    update_resource,
)
from .topics import (
    create_topic,
    delete_topic,
    delete_topic_subtree,
    expand_subtrees,
    find_parent_topic_ids,
    get_subtree,
    get_topic,
    list_children,
    list_root_topics,
    update_topic,
)

__all__ = [
    # topics
    "create_topic",
    "get_topic",
    "list_root_topics",
    "list_children",
    "get_subtree",
    "expand_subtrees",
    "find_parent_topic_ids",
    "update_topic",
    "delete_topic",
    "delete_topic_subtree",
    # entries
    "EntrySortKey",
    "count_entries",
    "count_entries_filtered",
    "create_entry",
    "get_entry",
    "list_entries",
    "list_entries_paginated",
    "update_entry",
    "delete_entry",
    "search_entries",
    # tags
    "create_tag",
    "list_tags",
    "tag_entry",
    "untag_entry",
    "get_entries_by_tag",
    # relations
    "CycleError",
    "add_relation",
    "remove_relation",
    "get_related_entries",
    "get_dependency_chain",
    # reviews
    "create_review_session",
    "get_review_session",
    "complete_review_session",
    "add_review_interaction",
    "list_review_interactions",
    "get_review_session_entries",
    "get_sessions_by_topics",
    "update_session_ephemeral",
    "update_session_instructions",
    "update_session_plan",
    "update_session_summary",
    "get_interaction_stats",
    # flashcards
    "activate_flashcard",
    "apply_fsrs_card",
    "apply_rating",
    "commit_fsrs_card",
    "count_flashcards",
    "count_flashcards_by_topic",
    "count_flashcards_by_topics",
    "count_flashcards_for_entries",
    "create_flashcard",
    "get_due_flashcards",
    "get_flashcard_entry_ids",
    "get_flashcards_by_ids",
    "link_flashcards_to_entry",
    "list_flashcards_by_entries",
    "list_flashcards_by_topic",
    "list_flashcards_for_entries",
    "list_flashcards_paginated",
    "to_fsrs_card",
    "unlink_flashcards_from_entry",
    # resolve
    "AmbiguousResource",
    "AmbiguousTopic",
    "get_topic_path",
    "resolve_resource",
    "resolve_topic",
    # resources
    "insert_sections",
    "link_chunks_to_sections",
    "add_chunks",
    "clear_chunks",
    "create_resource",
    "delete_resource",
    "compute_section_end_offsets",
    "get_chunks",
    "get_chunks_for_section",
    "get_resource",
    "get_resource_with_content_and_sections",
    "get_section_resource_ids",
    "count_resources",
    "link_resource_to_topic",
    "list_resources",
    "list_resources_for_topic",
    "list_resources_paginated",
    "unlink_resource_from_topic",
    "update_resource",
]
