"""add FSRS state to flashcard

Revision ID: 1aae56295c18
Revises: 9a530f261b65
Create Date: 2026-04-21 19:58:01.197196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import rhizome.db.models


# revision identifiers, used by Alembic.
revision: str = '1aae56295c18'
down_revision: Union[str, Sequence[str], None] = '9a530f261b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fsrs_state', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('fsrs_step', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('stability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('due', rhizome.db.models.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_review', rhizome.db.models.UTCDateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_flashcard_due'), ['due'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_due'))
        batch_op.drop_column('last_review')
        batch_op.drop_column('due')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('stability')
        batch_op.drop_column('fsrs_step')
        batch_op.drop_column('fsrs_state')

    # ### end Alembic commands ###
