"""add entry_id index to flashcard_entry

Revision ID: cf4a95586cc8
Revises: b8fe7cb59ea6
Create Date: 2026-05-22 12:21:23.023472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4a95586cc8'
down_revision: Union[str, Sequence[str], None] = 'b8fe7cb59ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_entry_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_entry_entry_id'))

    # ### end Alembic commands ###
